// REFERENCE/components/CriterionEditor.vue
<script setup lang="ts">
import { computed, watch } from 'vue'
import type { Criterion } from '@/lib/types'
import type { SystemMapData } from '@/lib/api'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import Vec3dInput from './Vec3dInput.vue'
import AutocompleteInput from './AutocompleteInput.vue'
import { Button } from '@/components/ui/button'
import { Trash2 } from 'lucide-vue-next'
import { Label } from '@/components/ui/label'
import { Card, CardContent } from '@/components/ui/card'
import { createDefaultCriterion } from '@/lib/quest'
import { Input } from '@/components/ui/input'
import { Switch } from './ui/switch'
import { v4 as uuidv4 } from 'uuid'

defineOptions({
  name: 'CriterionEditor',
})

const props = defineProps<{
  modelValue: Criterion
  systemMapData: SystemMapData | null
}>()

const emit = defineEmits<{
  (e: 'update:modelValue', value: Criterion): void
  (e: 'delete'): void
}>()

const criterion = computed({
  get: () => props.modelValue,
  set: (newValue) => {
    emit('update:modelValue', newValue)
  },
})

watch(criterion, (newCriterion) => {
  if (!props.systemMapData) return

  const type = newCriterion.type
  if (type === 'VisitStationCriterion' || type === 'RideToStationCriterion' || type === 'RideLineToStationCriterion') {
    const stationName = newCriterion.stationName
    if (stationName && props.systemMapData.stationNameToId[stationName]) {
      const stationId = props.systemMapData.stationNameToId[stationName]
      if (stationId !== undefined && stationName !== stationId) { // Prevent infinite loop if name is already ID
        newCriterion.stationName = stationId
        // toast.info('Station name resolved', {
        //   description: `"${stationName}" was automatically converted to ID "${stationId}". This is for that future renames won't break existing quests.`,
        // })
      }
    }
  }
}, { deep: true })

const stationItems = computed(() => props.systemMapData?.stationNamesAndIds ?? [])
const routeItems = computed(() => props.systemMapData?.routeNames ?? [])

const criterionTypes: Criterion['type'][] = [
  'RideLineCriterion',
  'VisitStationCriterion',
  'RideToStationCriterion',
  'RideLineToStationCriterion',
  'ManualTriggerCriterion',
  'InBoundsCriterion',
  'OverSpeedCriterion',
  'TeleportDetectCriterion',
  'ConstantCriterion',
  'Descriptor',
  'AndCriterion',
  'OrCriterion',
  'NotCriterion',
  'LatchingCriterion',
  'RisingEdgeAndConditionCriterion',
]

function handleTypeChange(newType: Criterion['type'] | null) {
  if (newType && newType !== criterion.value.type) {
    criterion.value = createDefaultCriterion(newType)
  }
}

function addCriterion(list: Criterion[]) {
  list.push(createDefaultCriterion('InBoundsCriterion'))
}

function deleteCriterion(list: Criterion[], index: number) {
  list.splice(index, 1)
}

const componentId = uuidv4()
</script>

<template>
  <Card class="relative">
    <div class="absolute top-4 right-4">
      <Button variant="ghost" size="icon" @click="$emit('delete')">
        <Trash2 class="h-4 w-4 text-red-500" />
      </Button>
    </div>
    <CardContent class="space-y-4">
      <div class="space-y-2">
        <Select :model-value="criterion.type" @update:model-value="(value) => handleTypeChange(value as Criterion['type'])">
          <SelectTrigger>
            <SelectValue placeholder="Select a condition type" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem v-for="type in criterionTypes" :key="type" :value="type">
              {{ type.replace('Criterion', '') }}
            </SelectItem>
          </SelectContent>
        </Select>
      </div>

      <div v-if="criterion.type === 'InBoundsCriterion'" class="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div class="space-y-2">
          <Label>Minimum Coordinates</Label>
          <Vec3dInput v-model="criterion.min" />
        </div>
        <div class="space-y-2">
          <Label>Maximum Coordinates</Label>
          <Vec3dInput v-model="criterion.max" />
        </div>
        <div class="space-y-2 md:col-span-2">
          <Label>Description</Label>
          <Input v-model="criterion.description" />
        </div>
      </div>

      <div v-if="criterion.type === 'OverSpeedCriterion'" class="space-y-2">
        <Label>Max Speed (m/s)</Label>
        <Input v-model.number="criterion.maxSpeedMps" type="number" />
      </div>

      <div v-if="criterion.type === 'TeleportDetectCriterion'" class="space-y-2">
        <p class="text-sm text-muted-foreground">This criterion is triggered whenever a player moved more than 166 meters in the last second (~ 600km/h).</p>
      </div>
      
      <div v-if="criterion.type === 'Descriptor'" class="space-y-2">
        <Label>Base Condition</Label>
        <CriterionEditor
          v-model="criterion.base"
          :system-map-data="systemMapData"
          :is-root="false"
        />
        <div class="space-y-2">
          <Label>Description (Overwrites Base Condition Description)</Label>
          <Input v-model="criterion.description" />
        </div>
      </div>

      <div v-if="criterion.type === 'RideLineCriterion'" class="space-y-2">
        <div class="space-y-2">
          <Label>Line Name</Label>
          <AutocompleteInput v-model="criterion.lineName" :items="routeItems" placeholder="Select a route" />
        </div>
      </div>
      
      <div v-if="criterion.type === 'VisitStationCriterion'" class="space-y-2">
        <div class="space-y-2">
          <Label>Station Name</Label>
          <AutocompleteInput v-model="criterion.stationName" :items="stationItems" placeholder="Select a station" />
        </div>
      </div>
      
      <div v-if="criterion.type === 'RideToStationCriterion'" class="space-y-2">
        <div class="space-y-2">
          <Label>Station Name</Label>
          <AutocompleteInput v-model="criterion.stationName" :items="stationItems" placeholder="Select a station" />
        </div>
      </div>

      <div v-if="criterion.type === 'RideLineToStationCriterion'" class="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div class="space-y-2">
          <Label>Line Name</Label>
          <AutocompleteInput v-model="criterion.lineName" :items="routeItems" placeholder="Select a route" />
        </div>
        <div class="space-y-2">
          <Label>Station Name</Label>
          <AutocompleteInput v-model="criterion.stationName" :items="stationItems" placeholder="Select a station" />
        </div>
      </div>

      <div v-if="criterion.type === 'ManualTriggerCriterion'" class="space-y-2">
        <p>ID: <code>{{ criterion.id }}</code></p>
        <div class="space-y-2">
          <Label>Description</Label>
          <Input v-model="criterion.description" placeholder="Describe how to manually trigger this step." />
        </div>
      </div>

      <div v-if="criterion.type === 'ConstantCriterion'" class="space-y-2">
        <div class="flex items-center space-x-2">
          <Switch :id="`constant-value-${componentId}`" v-model="criterion.value" />
          <label
            :for="`constant-value-${componentId}`"
            class="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
          >
            Value
          </label>
        </div>
        <div class="space-y-2">
          <Label>Description</Label>
          <Input v-model="criterion.description" />
        </div>
      </div>

      <div v-if="criterion.type === 'AndCriterion' || criterion.type === 'OrCriterion'" class="space-y-4">
        <h3 class="text-md font-semibold">Conditions</h3>
        <div class="space-y-4">
          <CriterionEditor
            v-for="(_, index) in criterion.criteria"
            :key="index"
            v-model="criterion.criteria[index]"
            :system-map-data="systemMapData"
            :is-root="false"
            @delete="deleteCriterion(criterion.criteria, index)"
          />
        </div>
        <Button variant="default" @click="addCriterion(criterion.criteria)">
          Add Condition
        </Button>
      </div>

      
      <div v-if="criterion.type === 'NotCriterion'" class="space-y-2">
        <Label>Base Condition</Label>
        <CriterionEditor
          v-model="criterion.base"
          :system-map-data="systemMapData"
          :is-root="false"
        />
        <div class="space-y-2">
          <Label>Description (Overwrites Base Condition Description)</Label>
          <Input v-model="criterion.description" />
        </div>
      </div>

      <div v-if="criterion.type === 'LatchingCriterion'" class="space-y-2">
        <Label>Base Condition</Label>
        <CriterionEditor
          v-model="criterion.base"
          :system-map-data="systemMapData"
          :is-root="false"
        />
      </div>

      <div v-if="criterion.type === 'RisingEdgeAndConditionCriterion'" class="space-y-4">
        <div class="space-y-2">
          <Label>Trigger Condition</Label>
          <CriterionEditor
            v-model="criterion.triggerCriteria"
            :system-map-data="systemMapData"
            :is-root="false"
          />
        </div>
        <div class="space-y-2">
          <Label>Condition</Label>
          <CriterionEditor
            v-model="criterion.conditionCriteria"
            :system-map-data="systemMapData"
            :is-root="false"
          />
        </div>
      </div>
    </CardContent>
  </Card>
</template>

// components/quest-editor/CriterionEditor.tsx
"use client";

import { useCallback, useEffect } from "react";
import {
  Dropdown,
  Option,
  Input,
  Label,
  Button,
  Switch,
  Text,
} from "@fluentui/react-components";
import { DeleteRegular, AddRegular } from "@fluentui/react-icons";
import { useSelector } from "react-redux";
import type { RootState } from "@/lib/store";
import type { Criterion, CriterionType } from "@/lib/types";
import { CRITERION_TYPES } from "@/lib/types";
import { createDefaultCriterion, criterionTypeLabel } from "@/lib/criterion";
import { Vec3dInput } from "./Vec3dInput";
import { AutocompleteInput } from "./AutocompleteInput";

const BORDER_COLORS = [
  "border-l-blue-400",
  "border-l-purple-400",
  "border-l-cyan-400",
  "border-l-pink-400",
  "border-l-amber-400",
];

interface CriterionEditorProps {
  value: Criterion;
  onChange: (value: Criterion) => void;
  onDelete?: () => void;
  depth?: number;
}

export function CriterionEditor({
  value,
  onChange,
  onDelete,
  depth = 0,
}: CriterionEditorProps) {
  const systemMap = useSelector((state: RootState) => state.systemMap.data);
  const stationItems = systemMap?.stationNamesAndIds ?? [];
  const routeItems = systemMap?.routeNames ?? [];
  const stationDisplayMap = systemMap?.stationIdToName ?? {};

  // Auto-resolve station names to IDs when the user picks from autocomplete
  useEffect(() => {
    if (!systemMap) return;
    if (
      value.type === "VisitStationCriterion" ||
      value.type === "RideToStationCriterion" ||
      value.type === "RideLineToStationCriterion"
    ) {
      const name = value.stationName;
      const resolved = systemMap.stationNameToId[name];
      if (resolved && resolved !== name) {
        onChange({ ...value, stationName: resolved });
      }
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps -- only re-run when the station value itself changes
  }, [value.type === "VisitStationCriterion" || value.type === "RideToStationCriterion" || value.type === "RideLineToStationCriterion" ? value.stationName : null, systemMap]);

  const handleTypeChange = useCallback(
    (newType: string) => {
      if (newType && newType !== value.type) {
        onChange(createDefaultCriterion(newType as CriterionType));
      }
    },
    [value.type, onChange]
  );

  const update = useCallback(
    (patch: Partial<Criterion>) => {
      onChange({ ...value, ...patch } as Criterion);
    },
    [value, onChange]
  );

  const borderColor = BORDER_COLORS[depth % BORDER_COLORS.length];

  return (
    <div className={`border-l-3 ${borderColor} pl-3 py-2 space-y-2`}>
      {/* Header: type selector + delete */}
      <div className="flex items-center gap-2">
        <Dropdown
          size="small"
          value={criterionTypeLabel(value.type)}
          selectedOptions={[value.type]}
          onOptionSelect={(_, d) => handleTypeChange(d.optionValue ?? "")}
          className="min-w-[180px]"
        >
          {CRITERION_TYPES.map((t) => (
            <Option key={t} value={t}>
              {criterionTypeLabel(t)}
            </Option>
          ))}
        </Dropdown>

        <div className="flex-1" />

        {onDelete && (
          <Button
            appearance="subtle"
            icon={<DeleteRegular />}
            size="small"
            onClick={onDelete}
            title="Remove"
          />
        )}
      </div>

      {/* Type-specific fields */}
      {value.type === "VisitStationCriterion" && (
        <AutocompleteInput
          label="Station Name"
          value={value.stationName}
          onChange={(v) => update({ stationName: v })}
          items={stationItems}
          placeholder="Select a station"
          displayMap={stationDisplayMap}
        />
      )}

      {value.type === "RideToStationCriterion" && (
        <AutocompleteInput
          label="Station Name"
          value={value.stationName}
          onChange={(v) => update({ stationName: v })}
          items={stationItems}
          placeholder="Select a station"
          displayMap={stationDisplayMap}
        />
      )}

      {value.type === "RideLineCriterion" && (
        <AutocompleteInput
          label="Line Name"
          value={value.lineName}
          onChange={(v) => update({ lineName: v })}
          items={routeItems}
          placeholder="Select a route"
        />
      )}

      {value.type === "RideLineToStationCriterion" && (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
          <AutocompleteInput
            label="Line Name"
            value={value.lineName}
            onChange={(v) => update({ lineName: v })}
            items={routeItems}
            placeholder="Select a route"
          />
          <AutocompleteInput
            label="Station Name"
            value={value.stationName}
            onChange={(v) => update({ stationName: v })}
            items={stationItems}
            placeholder="Select a station"
            displayMap={stationDisplayMap}
          />
        </div>
      )}

      {value.type === "InBoundsCriterion" && (
        <>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
            <Vec3dInput
              label="Minimum Coordinates"
              value={value.min}
              onChange={(v) => update({ min: v })}
            />
            <Vec3dInput
              label="Maximum Coordinates"
              value={value.max}
              onChange={(v) => update({ max: v })}
            />
          </div>
          <div className="flex flex-col gap-1">
            <Label size="small">Description</Label>
            <Input
              size="small"
              value={value.description}
              onChange={(_, d) => update({ description: d.value })}
            />
          </div>
        </>
      )}

      {value.type === "OverSpeedCriterion" && (
        <div className="flex flex-col gap-1">
          <Label size="small">Max Speed (m/s)</Label>
          <Input
            size="small"
            type="number"
            value={String(value.maxSpeedMps)}
            onChange={(_, d) =>
              update({ maxSpeedMps: parseFloat(d.value) || 0 })
            }
          />
        </div>
      )}

      {value.type === "TeleportDetectCriterion" && (
        <Text size={200} className="text-gray-500">
          Triggered when a player moves more than 166 meters in one second (~600km/h).
        </Text>
      )}

      {value.type === "ManualTriggerCriterion" && (
        <>
          <Text size={200}>
            ID: <code className="bg-gray-100 px-1 rounded text-xs">{value.id}</code>
          </Text>
          <div className="flex flex-col gap-1">
            <Label size="small">Description</Label>
            <Input
              size="small"
              value={value.description}
              onChange={(_, d) => update({ description: d.value })}
              placeholder="Describe how to manually trigger this step."
            />
          </div>
        </>
      )}

      {value.type === "ConstantCriterion" && (
        <div className="space-y-2">
          <Switch
            checked={value.value}
            onChange={(_, d) => update({ value: d.checked })}
            label="Value"
          />
          <div className="flex flex-col gap-1">
            <Label size="small">Description</Label>
            <Input
              size="small"
              value={value.description}
              onChange={(_, d) => update({ description: d.value })}
            />
          </div>
        </div>
      )}

      {value.type === "Descriptor" && (
        <>
          <div className="flex flex-col gap-1">
            <Label size="small">Base Condition</Label>
            <CriterionEditor
              value={value.base}
              onChange={(base) => onChange({ ...value, base })}
              depth={depth + 1}
            />
          </div>
          <div className="flex flex-col gap-1">
            <Label size="small">Description (overwrites base description)</Label>
            <Input
              size="small"
              value={value.description}
              onChange={(_, d) => update({ description: d.value })}
            />
          </div>
        </>
      )}

      {(value.type === "AndCriterion" || value.type === "OrCriterion") && (
        <div className="space-y-2">
          <Label size="small">Conditions</Label>
          {value.criteria.map((child, index) => (
            <CriterionEditor
              key={index}
              value={child}
              onChange={(newChild) => {
                const updated = [...value.criteria];
                updated[index] = newChild;
                onChange({ ...value, criteria: updated });
              }}
              onDelete={() => {
                const updated = value.criteria.filter((_, i) => i !== index);
                onChange({ ...value, criteria: updated });
              }}
              depth={depth + 1}
            />
          ))}
          <Button
            size="small"
            icon={<AddRegular />}
            onClick={() =>
              onChange({
                ...value,
                criteria: [
                  ...value.criteria,
                  createDefaultCriterion("InBoundsCriterion"),
                ],
              })
            }
          >
            Add Condition
          </Button>
        </div>
      )}

      {value.type === "NotCriterion" && (
        <>
          <div className="flex flex-col gap-1">
            <Label size="small">Base Condition</Label>
            <CriterionEditor
              value={value.base}
              onChange={(base) => onChange({ ...value, base })}
              depth={depth + 1}
            />
          </div>
          <div className="flex flex-col gap-1">
            <Label size="small">Description (overwrites base description)</Label>
            <Input
              size="small"
              value={value.description}
              onChange={(_, d) => update({ description: d.value })}
            />
          </div>
        </>
      )}

      {value.type === "LatchingCriterion" && (
        <div className="flex flex-col gap-1">
          <Label size="small">Base Condition</Label>
          <CriterionEditor
            value={value.base}
            onChange={(base) => onChange({ ...value, base })}
            depth={depth + 1}
          />
        </div>
      )}

      {value.type === "RisingEdgeAndConditionCriterion" && (
        <div className="space-y-2">
          <div className="flex flex-col gap-1">
            <Label size="small">Trigger Condition</Label>
            <CriterionEditor
              value={value.triggerCriteria}
              onChange={(triggerCriteria) =>
                onChange({ ...value, triggerCriteria })
              }
              depth={depth + 1}
            />
          </div>
          <div className="flex flex-col gap-1">
            <Label size="small">Condition</Label>
            <CriterionEditor
              value={value.conditionCriteria}
              onChange={(conditionCriteria) =>
                onChange({ ...value, conditionCriteria })
              }
              depth={depth + 1}
            />
          </div>
        </div>
      )}
    </div>
  );
}
